name: CI

on:
  push: {branches: '**'}

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        folder:
            - '.'
            - 'e2e/bzlmod-ecsact-sdk'

    runs-on: ${{ matrix.os }}
   
    steps:
      - uses: actions/checkout@v4
      - name: bazel test //...
        working-directory: ${{ matrix.folder }}
        run: bazelisk --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
