name: CI

on:
  push: {branches: '**'}

jobs:
  test-bzlmod-ecsact-sdk:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ecsact-dev/github-action@20dce3b35d5212e824ef00d8737ec4953ce3e5d3
      - uses: actions/checkout@v4
      - name: bazel test //...
        working-directory: e2e/bzlmod-ecsact-sdk
        run: bazelisk --bazelrc=../../.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
