name: CI

on:
  push: {branches: '**'}

jobs:
  test-bzlmod-ecsact-sdk:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ecsact-dev/github-action@8919305619f476ac32e8310bf68dbd4b4b820cf3
      - uses: actions/checkout@v4
      - name: bazel test //...
        working-directory: e2e/bzlmod-ecsact-sdk
        run: bazelisk --bazelrc=../../.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
