name: CI

on:
  push: {branches: '**'}

jobs:
  test-linux:
    strategy:
      matrix:
        folder:
            - '.'
            - 'e2e/bzlmod-ecsact-sdk'

    runs-on: ubuntu-latest
   
    steps:
      - run: curl https://ecsact.dev/install.sh -sSfL | sh
      - uses: actions/checkout@v4
      - name: bazel test //...
        working-directory: ${{ matrix.folder }}
        run: bazelisk --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
