name: CI

on:
  push: {branches: '**'}

jobs:
  test-bzlmod-ecsact-sdk:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ecsact-dev/github-action@eec47f6e1a186ec7237af81a04ac579f0cc634b7
      - uses: actions/checkout@v4
      - name: bazel test //...
        working-directory: e2e/bzlmod-ecsact-sdk
        run: bazelisk --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
